#include "config.h"
bool followLine();
void driveInCorridorUntilIntersection();
void handleIntersection();
void followLineCarefullyUntilIntersection();
bool detectIntersection();
void grabBall();
void turnLeftUntilLine();
void turnRightUntilLine();
